### ISSUE TITLE
Memcached should be decorated instead of extending

### ISSUE THREAD

**Issue by rokerkony** [mullanaphy/cache-bundle#1]
Hi, I tried to change storage from Memcache to Memcached and I think it's not possible (or maybe I set something wrong).

Issues:
- PHY\CacheBundle\Cache\Memcached is extending \Memcached, but it has other implementation and methods are incompatible - so my point is, it should to decorate \Memcached not to extend
  `Strict standards: Declaration of PHY\CacheBundle\Cache\Memcached\Memcached::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)`
- in constructor you are checking for key server but one line below you're trying to add servers and also you are not calling parent's constructor, which is always bad in extending

**Comment by mullanaphy** [comment]
Not a bad idea, no reason this can't be done in similar to Redis which was added recently. The Memcached portion hasn't been updated in well over a year and there's no parent::__construct() since \Memcached' constructor was only persistent_id and personally didn't have a need.

So yeah, I'm down for not extending \Memcached and \Memcache, might as well add geInstance(); and up a minor version.

If you have any changes I don't mind doing a pr, otherwise I'm just snowed in today so can work on it.

**Comment by mullanaphy** [comment]
Okay, I upped the version to 0.1.0 (78734309532719ad02aefbc4724056740e55ad55), Memcached and Memcache both are instances on Cache\Memcached and Cache\Memcache respectively. Now you can also do:

``` php
$memcached = $cache->getInstance();
var_dump($memcached);
```

In cases where you might need the raw instance.

I might need to change the README.md and a side note I did update the tests to actually work so hurray on that.

**Comment by rokerkony** [comment]
wooow... you're faster than I expected ... I made one comment - but nice work ;)

**Comment by mullanaphy** [comment]
Thanks and thanks again for letting me know about the issue. Fixed the typo as well, today I'll look to add some tests to help protect against typos like that.
